# Generated by Django 6.0.2 on 2026-02-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('preacher', models.CharField(max_length=100, verbose_name='Predicador')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('audio_file', models.FileField(upload_to='sermons/audio/', verbose_name='Archivo de audio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sermons/images/', verbose_name='Imagen')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('bible_text', models.CharField(blank=True, max_length=100, verbose_name='Texto bíblico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sermón',
                'verbose_name_plural': 'Sermones',
                'ordering': ['-date'],
            },
        ),
    ]
