# Generated by Django 6.0.2 on 2026-02-26 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('image', models.ImageField(blank=True, null=True, upload_to='devocionales/', verbose_name='Imagen')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Devocional',
                'verbose_name_plural': 'Devocionales',
                'ordering': ['-published_date'],
            },
        ),
    ]
