# Generated by Django 6.0.2 on 2026-02-26 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name1', models.CharField(max_length=100, verbose_name='Primer apellido')),
                ('last_name2', models.CharField(blank=True, max_length=100, verbose_name='Segundo apellido')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('baptism_date', models.DateField(verbose_name='Fecha de bautismo')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('reparto', models.CharField(max_length=100, verbose_name='Reparto')),
                ('municipality', models.CharField(default='Guanabacoa', max_length=100, verbose_name='Municipio')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Miembro activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'ordering': ['last_name1', 'last_name2', 'first_name'],
            },
        ),
    ]
