# Generated by Django 6.0.2 on 2026-02-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='estado',
            field=models.CharField(choices=[('miembro', 'Miembro'), ('congregado', 'Congregado')], default='congregado', max_length=20, verbose_name='Estado'),
        ),
    ]
