# Generated by Django 6.0.2 on 2026-02-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='baptism_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de bautismo'),
        ),
    ]
